### ISSUE TITLE
Login doesn't work on a fresh installation

### ISSUE THREAD

**Issue by felixding** [armm77/nextspace-iso-installer#2]
This is the config:
![Screenshot 2022-02-05 113902](https://user-images.githubusercontent.com/111456/152630232-af752c68-701d-4c51-b632-534b1a5ffda3.png)

This is what happened after inputting password and hitting Enter:
https://user-images.githubusercontent.com/111456/152630239-30598383-cdae-4916-b3a5-b8b4bf83102a.mp4

**Comment by armm77** [comment]
hi @felixding, I did several installations but I can't reproduce the behavior, the user's password is nextspace.

**Comment by felixding** [comment]
It finally worked! Don't really know why it didn't on the first two installs.

This is really great!
